### ISSUE TITLE
Investigate loki and other visual regression testing tools for storybook

### ISSUE THREAD

**Issue by gidjin** [trussworks/react-uswds#40] opened 2020-03-26 23:21 UTC
As part of automated testing, I recommend we set up https://loki.js.org/ to run against storybook in this project, and the corresponding CircleCI job to run it so that contributions and improvements do not break the visual appearance of components unexpected.

**Comment by haworku** [comment] 2020-05-20 18:18
From my understanding to scope of this ticket has expanded.  The goal is now to review options visual regression testing (from [this list](https://storybook.js.org/docs/testing/automated-visual-testing/)) and then implement one. 

Capturing a few more points from Slack discussions:

- We want to specifically test our storybook stories, checking for visual regressions in components as rendered in stories. This is the use case.
- There are concerns about having to use docker to run `loki` tests effectively. This could be a barrier to entry for devs using this tool.
- As possible, we want automation for this type of testing as opposed to putting the onus on the developer to make sure they run a tool and check in new screenshots when there changes
- Whatever decisions are made there is a desire to document it thoroughly (maybe via ADR).

**Comment by eamahanna** [comment] 2020-05-20 23:15
@haworku your summary above is spot on. I am currently evaluating alternatives to loki for visual regression testing of story book. There are numerous tools that can do this, so I have narrowed down the research to the [tools listed within the storybook docs](https://storybook.js.org/docs/testing/automated-visual-testing/). 

To further eliminate options, I am only reviewing libraries/services that are open source or free to open source libraries. Additionally, I an only looking into libraries/services that have existing integration options for storybook. The potential options are listed below:

Open Source Options
- [Creevey](https://github.com/wKich/creevey)
- [Loki](https://loki.js.org/)
- [StoryShots + Puppeteer](https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-puppeteer)

Free to Open Source Projects
- [Applitools](https://applitools.com/storybook/)
- [Chromatic](https://www.chromatic.com/)
- [Happo](https://happo.io/)

I believe the next step in narrowing down selection is determining whether we would like to continue with one of the open source options or the free to open source options. In general, the services that normally charge a fee have significantly better documentation than the open source alternatives, interactive UIs, and can easily integrate with github and circleci. However, the initial setup of non-open source options will require a little more effort because all of them require contact and communication with each of the companies to qualify react-uswds for the free open source specials. Additionally, the non-open source options feel potentially a little excessive in terms of bells and whistles for what this library needs. 

I would love to hear people's opinions and perspective on this.

**Comment by eamahanna** [comment] 2020-05-20 23:18
I am currently working on a document (notes really at this point) that highlight some of the benefits of each tool.

**Comment by eamahanna** [comment] 2020-05-21 00:06
Here are a lot of notes for the potential options:

## Open Source

### Creevey (open source)
* Not a ton of documentation
* https://github.com/wKich/creevey/tree/master/examples/react
* Unclear on if possible and how to integrate with circleci and github
* Tests multiple browsers (Chrome, IE 11, Firefox )

### Loki (open source)
* https://loki.js.org/getting-started.html
* Supported platforms (chrome in docker, local chrome, ios simulator, android emulator)
* Has decent documentation
* Requires dev to manually test in docker before each commit or else have the chance of the build failing in circleci
* It seems to be one of the more adopted open source services/tools so there is a fair amount of community around it
* Tightly linked with docker

### StoryShots + Puppeteer (open source)
* https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-puppeteer
* Unclear on how to integrate with github and circleci
* Looks fairly customizable, but there would be a decent amount of work to configure
* Have to write tests for each of your stories……...yuck…..I could be wrong but I think that is what I read

## Free to Open Source Projects

### Applitools (free for open source)
* https://applitools.com/storybook/
* Integrates with GH and circleci
* Tests multiple browsers (Chrome, IE, Firefox, Safari, and Edge)
* Responsive testing
* Workflow - validates baseline images with each github PR and in CI builds, can also be done manually by dev during development.
* Can view testing results in a UI (similar to storybooks)
* Docs demoing use of applitools and storybook https://applitools.com/blog/visual-test-react-storybook/
* Results are hosted on applitools server (I think)

### Chromatic (free for open source)
* https://www.chromatic.com/docs/setup
* Developed by storybook
* Integrates with GH and circleci
* Tests multiple browsers (chrome, firefox, IE 11)
* UI interface that allows collaboration
*  _“Help teams review UI changes together. The online review process allows team members to review and confirm changes without pulling code.”_
* Shows component history - each component is tracked with every commit 
* Everytime code is pushed the components within storybook are uploaded to Chromatic, so everyone on the team can view them. You don’t need to pull code to see them….not sure how this works with different branches ect.

### Happo (free for open source)
* https://docs.happo.io/docs/storybook
* https://medium.com/happo-io/cross-browser-screenshot-testing-with-happo-io-and-storybook-bfb0b848a97a
* Integrates with circleci and github
* Tests multiple browsers (firefox, chrome, IE 11, edge, safari, ios-safari)
* Results and base images are stored on happo.io server and can be accessed through UI

**Comment by suzubara** [comment] 2020-05-21 16:40
Thanks @eamahanna for doing all of this research!! I did a brief look at the tools you linked, and here are my thoughts.

First, I'm of the mind we should pick one of the enterprise tools that is free for open source -- they all look like they'll require less config upfront, they should have better support and stability by nature, and why not take advantage of our open source status?

Second, I'm inclined to go with Chromatic -- I like the idea of us investing further in Storybook, and we know that Storybook will have first-class support. It's unfortunate they don't have Safari/mobile Safari testing, I want to look into whether they are planning to add that. But also the collaboration tools seem top-notch, especially for getting designer sign-off on components.

that's my two cents!

**Comment by eamahanna** [comment] 2020-05-21 16:45
@suzubara I tend to agree. I think my first instinct was also to double down on storybook. I'm not sure how important it is to have safari testing. I can do more research into chromatic and see if it is mentioned. I will also look into what they need to get us free access :)

**Comment by eamahanna** [comment] 2020-05-22 16:20
@suzubara I just heard back from chromatic. Unfortunately the open source free plan only allows from chrome testing. It also has a snapshot limit of 35,000 per month. Given it only tests in chrome, I am not sure the collaboration tools out weight being able to in different browsers. What are your thoughts?

**Comment by suzubara** [comment] 2020-05-27 18:55
Oh no that's really disappointing :( it makes sense though, cross-browser automated testing gets expensive. Maybe we can find out from Applitools & Happo if their open source plans have similar restrictions?

**Comment by eamahanna** [comment] 2020-05-27 19:34
I reached out to Applitools and Happo yesterday and am waiting to hear back about their open source plans :)

**Comment by eamahanna** [comment] 2020-05-27 20:21
* Chromatic's free open source "plan" only allows for testing in chrome and limits usage to 35,000 snapshots per month
* Applitools free open source "plan" limits snapshots 100 checkpoints/screenshots per month and allows for cross browser testing
* Happo's free open source plan allows for cross browser testing and has no hard limit on usage. They reserve the right to limit usage. "In general, if your open-source project stays below something like 20 pull requests per day, you should be okay."

**Comment by eamahanna** [comment] 2020-06-01 18:07
Given Happo did not have any hard usage limit, provided github and circleci integrations and numerous browsers to test, Happo was selected for implementation.

**Comment by eamahanna** [comment] 2020-06-04 17:41
Happo is merged in

**Closed by eamahanna** 2020-06-04 17:41 UTC
Labels: status: needs requirements, type: feature
